name: Lint PR Title example

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  pr-lint:
    uses: Lendable/github-actions/.github/workflows/pull-request-lint.yml@main
    with:
      lint-rules-path: examples/pr-lint/example-lint-rules.js
