name: Build

on:
  pull_request:
  push:
    branches:
      - main

  strategy:
    matrix:
      dependencies:
        - lowest
        - highest
        - locked
      php-version:
        - "8.0"
        - "8.1"
        - "8.2"
      os:
        - ubuntu-latest

jobs:
  build:
    uses: Lendable/github-actions/.github/workflows/ci.yaml@main
    with:
      composer-dependencies: ${{ matrix.dependencies }}
      php-version: "${{ matrix.php-version }}"
      code-style-php-version: "8.1"
